### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by dumpydev** [R0rt1z2/oplus-unlock#2]
So, I've tried to install this on windows and I've found it pretty hard.
I ran the command to install and tried to run
```
oplus-unlock
``` 
nothing happened.....

Not sure what im missing.

**Comment by R0rt1z2** [comment]
> So, I've tried to install this on windows and I've found it pretty hard. I ran the command to install and tried to run
> 
> ```
> oplus-unlock
> ```
> 
> nothing happened.....
> 
> Not sure what im missing.

Has the `pip` command been successful? To be honest, I never tried to install the tool on Windows, so I don't know if it will work. Anyway, you can clone the repository and run the tool from there.

**Comment by dumpydev** [comment]
yeah the pip worked. however i ran 
```
refresh-env 
```
(refreshes the environment variables on windows)
and it said unrecognized command.
I made sure that python was in path.
Might try use this on a linux liveusb :p

**Comment by R0rt1z2** [comment]
In case you still want to run the tool under Windows, I created a (dirty) workaround. The following command should automatically set up everything so you don't really need to manually call the script.
```powershell
Invoke-WebRequest https://cdn.r0rt1z2.com/oplus-unlock/Install.ps1 | Invoke-Expression
```
