### ISSUE TITLE
Patched LK doesn't boot on Oppo A91

### ISSUE THREAD

**Issue by Nomz420** [R0rt1z2/oplus-unlock#3]
I patched the LK for Oppo A91 and flashed it, but it didn't boot.
The phone is unlocked. Does this phone just refuse to boot modified LK?

```
[nomz@archbox sf_vm_share]$ oplus-unlock lk.bin -o patched-lk.bin
[*]: Magic        = 0x58881688
[*]: Size         = 2346580
[*]: Name         = lk
[*]: Load address = 0x57000000
[*]: Mode         = 0xffffffff
[*]: Sequence     = f0b5adf5925d (0x64ef8)
[+]: Sucessfully enabled fastboot. Check patched-lk.bin!
```
LK files: [lk.zip](https://github.com/R0rt1z2/oplus-unlock/files/9903227/lk.zip)

**Comment by R0rt1z2** [comment]
> The phone is unlocked
Does this mean that you used the mtkclient unlock option? If so, what version of Android does this device use?

**Comment by Nomz420** [comment]
> Does this mean that you used mtkclient's [unlock option](https://github.com/bkerler/mtkclient#unlock-bootloader)? 

Yes.

> If so, what version of Android does this device use?

Android 11 (ColorOS 11.1)

**Comment by R0rt1z2** [comment]
> > Does this mean that you used mtkclient's [unlock option](https://github.com/bkerler/mtkclient#unlock-bootloader)?
> 
> Yes.
> 
> > If so, what version of Android does this device use?
> 
> Android 11 (ColorOS 11.1)

In that case, it'is very likely that the images are being verified (by either the preloader or bootrom itself). After flashing the modified LK and trying to boot the device, can you dump the _expdb_ partition with mtkclient (`mtk r expdb expd.bin`) and upload it here?

**Comment by Nomz420** [comment]
[expdb.zip](https://github.com/R0rt1z2/oplus-unlock/files/9922967/expdb.zip)

**Comment by R0rt1z2** [comment]
> [expdb.zip](https://github.com/R0rt1z2/oplus-unlock/files/9922967/expdb.zip)

I'm sorry to tell you that your preloader checks against the LK's signature and therefore your device **is not supported by this tool**.
```
[PART] load "lk" from 0x000000002AD00200 (dev) to 0x57000000 (mem) [SUCCESS]
[PART] load speed: 229158KB/s, 2346580 bytes, 10ms
[PART] img vfy...[SBC] img auth fail(0x101004)
```
